SOILWAT2: SW_Output.h File Reference
SW_Output.h File Reference
Data Structures
struct SW_OUTPUT
Macros
#define SW_WETHR "WTHR"
#define SW_TEMP "TEMP"
#define SW_PRECIP "PRECIP"
#define SW_SOILINF "SOILINFILT"
#define SW_RUNOFF "RUNOFF"
#define SW_ALLH2O "ALLH2O"
#define SW_VWCBULK "VWCBULK"
#define SW_VWCMATRIC "VWCMATRIC"
#define SW_SWCBULK "SWCBULK"
#define SW_SWABULK "SWABULK"
#define SW_SWAMATRIC "SWAMATRIC"
#define SW_SWA "SWA"
#define SW_SWPMATRIC "SWPMATRIC"
#define SW_SURFACEW "SURFACEWATER"
#define SW_TRANSP "TRANSP"
#define SW_EVAPSOIL "EVAPSOIL"
#define SW_EVAPSURFACE "EVAPSURFACE"
#define SW_INTERCEPTION "INTERCEPTION"
#define SW_LYRDRAIN "LYRDRAIN"
#define SW_HYDRED "HYDRED"
#define SW_ET "ET"
#define SW_AET "AET"
#define SW_PET "PET"
#define SW_WETDAY "WETDAY"
#define SW_SNOWPACK "SNOWPACK"
#define SW_DEEPSWC "DEEPSWC"
#define SW_SOILTEMP "SOILTEMP"
#define SW_ALLVEG "ALLVEG"
#define SW_ESTAB "ESTABL"
#define SW_OUTNKEYS 29 /* must also match number of items in enum (minus eSW_NoKey and eSW_LastKey) */
#define SW_DAY "DY"
#define SW_WEEK "WK"
#define SW_MONTH "MO"
#define SW_YEAR "YR"
#define SW_OUTNPERIODS 4 /* must match with enum */
#define SW_SUM_OFF "OFF" /* don't output */
#define SW_SUM_SUM "SUM" /* sum for period */
#define SW_SUM_AVG "AVG" /* arith. avg for period */
#define SW_SUM_FNL "FIN" /* value on last day in period */
#define SW_NSUMTYPES 4
#define ForEachOutKey(k) for((k)=eSW_NoKey+1; (k)<eSW_LastKey; (k)++)
#define ForEachSWC_OutKey(k) for((k)=eSW_AllH2O; (k)<=eSW_SnowPack; (k)++)
#define ForEachWTH_OutKey(k) for((k)=eSW_AllWthr; (k)<=eSW_Precip; (k)++)
#define ForEachVES_OutKey(k) for((k)=eSW_AllVeg; (k)<=eSW_Estab; (k)++)
#define ForEachOutPeriod(k) for((k)=eSW_Day; (k)<=eSW_Year; (k)++)
Enumerations
enum OutKey {
eSW_NoKey = -1, eSW_AllWthr, eSW_Temp, eSW_Precip,
eSW_SoilInf, eSW_Runoff, eSW_AllH2O, eSW_VWCBulk,
eSW_VWCMatric, eSW_SWCBulk, eSW_SWABulk, eSW_SWAMatric,
eSW_SWA, eSW_SWPMatric, eSW_SurfaceWater, eSW_Transp,
eSW_EvapSoil, eSW_EvapSurface, eSW_Interception, eSW_LyrDrain,
eSW_HydRed, eSW_ET, eSW_AET, eSW_PET,
eSW_WetDays, eSW_SnowPack, eSW_DeepSWC, eSW_SoilTemp,
eSW_AllVeg, eSW_Estab, eSW_LastKey
}
enum OutPeriod { eSW_Day, eSW_Week, eSW_Month, eSW_Year }
enum OutSum { eSW_Off, eSW_Sum, eSW_Avg, eSW_Fnl }
Functions
void SW_OUT_construct (void)
void SW_OUT_new_year (void)
void SW_OUT_read (void)
void SW_OUT_sum_today (ObjType otyp)
void SW_OUT_write_today (void)
void SW_OUT_write_year (void)
void SW_OUT_close_files (void)
void SW_OUT_flush (void)
Macro Definition Documentation
#define ForEachOutKey (k) for((k)=eSW_NoKey+1; (k)<eSW_LastKey; (k)++)
Referenced by create_col_headers(), SW_OUT_construct(), SW_OUT_new_year(), SW_OUT_read(), and SW_OUT_write_today().
#define ForEachOutPeriod (k) for((k)=eSW_Day; (k)<=eSW_Year; (k)++)
Referenced by SW_OUT_sum_today().
#define ForEachSWC_OutKey (k) for((k)=eSW_AllH2O; (k)<=eSW_SnowPack; (k)++)
#define ForEachVES_OutKey (k) for((k)=eSW_AllVeg; (k)<=eSW_Estab; (k)++)
#define ForEachWTH_OutKey (k) for((k)=eSW_AllWthr; (k)<=eSW_Precip; (k)++)
#define SW_AET "AET"
#define SW_ALLH2O "ALLH2O"
#define SW_ALLVEG "ALLVEG"
#define SW_DAY "DY"
#define SW_DEEPSWC "DEEPSWC"
#define SW_ESTAB "ESTABL"
#define SW_ET "ET"
#define SW_EVAPSOIL "EVAPSOIL"
#define SW_EVAPSURFACE "EVAPSURFACE"
#define SW_HYDRED "HYDRED"
#define SW_INTERCEPTION "INTERCEPTION"
#define SW_LYRDRAIN "LYRDRAIN"
#define SW_MONTH "MO"
#define SW_NSUMTYPES 4
#define SW_OUTNKEYS 29 /* must also match number of items in enum (minus eSW_NoKey and eSW_LastKey) */
Referenced by SW_OUT_read(), and SW_OUT_write_today().
#define SW_OUTNPERIODS 4 /* must match with enum */
#define SW_PET "PET"
#define SW_PRECIP "PRECIP"
#define SW_RUNOFF "RUNOFF"
#define SW_SNOWPACK "SNOWPACK"
#define SW_SOILINF "SOILINFILT"
#define SW_SOILTEMP "SOILTEMP"
#define SW_SUM_AVG "AVG" /* arith. avg for period */
#define SW_SUM_FNL "FIN" /* value on last day in period */
#define SW_SUM_OFF "OFF" /* don't output */
#define SW_SUM_SUM "SUM" /* sum for period */
#define SW_SURFACEW "SURFACEWATER"
#define SW_SWA "SWA"
#define SW_SWABULK "SWABULK"
#define SW_SWAMATRIC "SWAMATRIC"
#define SW_SWCBULK "SWCBULK"
#define SW_SWPMATRIC "SWPMATRIC"
#define SW_TEMP "TEMP"
#define SW_TRANSP "TRANSP"
#define SW_VWCBULK "VWCBULK"
#define SW_VWCMATRIC "VWCMATRIC"
#define SW_WEEK "WK"
#define SW_WETDAY "WETDAY"
#define SW_WETHR "WTHR"
#define SW_YEAR "YR"
Enumeration Type Documentation
enum OutKey
Enumerator
eSW_NoKey
eSW_AllWthr
eSW_Temp
eSW_Precip
eSW_SoilInf
eSW_Runoff
eSW_AllH2O
eSW_VWCBulk
eSW_VWCMatric
eSW_SWCBulk
eSW_SWABulk
eSW_SWAMatric
eSW_SWA
eSW_SWPMatric
eSW_SurfaceWater
eSW_Transp
eSW_EvapSoil
eSW_EvapSurface
eSW_Interception
eSW_LyrDrain
eSW_HydRed
eSW_ET
eSW_AET
eSW_PET
eSW_WetDays
eSW_SnowPack
eSW_DeepSWC
eSW_SoilTemp
eSW_AllVeg
eSW_Estab
eSW_LastKey
enum OutPeriod
Enumerator
eSW_Day
eSW_Week
eSW_Month
eSW_Year
enum OutSum
Enumerator
eSW_Off
eSW_Sum
eSW_Avg
eSW_Fnl
Function Documentation
void SW_OUT_close_files (void)
Referenced by SW_CTL_main().
void SW_OUT_construct (void)
Referenced by SW_CTL_init_model().
void SW_OUT_flush (void)
Referenced by SW_CTL_run_current_year().
void SW_OUT_new_year (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_OUT_read (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_OUT_sum_today (ObjType otyp)
Referenced by stat_Output_Yearly_CSV_Summary(), and SW_OUT_flush().
void SW_OUT_write_today (void)
Referenced by stat_Output_Yearly_CSV_Summary(), and SW_OUT_flush().
void SW_OUT_write_year (void)