SOILWAT2: SW_Flow_lib.h File Reference
SW_Flow_lib.h File Reference
Data Structures
struct ST_RGR_VALUES
Macros
#define MAX_WINTSTCR (vegcov * .1)
#define MAX_WINTFOR (ppt)
#define MAX_WINTLIT (blitter * .2)
#define TCORRECTION 0.02
#define FREEZING_TEMP_C -1.
#define FUSIONHEAT_H2O 80.
#define MIN_VWC_TO_FREEZE 0.13
Functions
void grass_intercepted_water (double *pptleft, double *wintgrass, double ppt, double vegcov, double scale, double a, double b, double c, double d)
void shrub_intercepted_water (double *pptleft, double *wintshrub, double ppt, double vegcov, double scale, double a, double b, double c, double d)
void tree_intercepted_water (double *pptleft, double *wintfor, double ppt, double LAI, double scale, double a, double b, double c, double d)
void forb_intercepted_water (double *pptleft, double *wintforb, double ppt, double vegcov, double scale, double a, double b, double c, double d)
void litter_intercepted_water (double *pptleft, double *wintlit, double blitter, double scale, double a, double b, double c, double d)
void infiltrate_water_high (double swc[], double drain[], double *drainout, double pptleft, unsigned int nlyrs, double swcfc[], double swcsat[], double impermeability[], double *standingWater)
double petfunc (unsigned int doy, double avgtemp, double rlat, double elev, double slope, double aspect, double reflec, double humid, double windsp, double cloudcov, double transcoeff)
double svapor (double temp)
void transp_weighted_avg (double *swp_avg, unsigned int n_tr_rgns, unsigned int n_layers, unsigned int tr_regions[], double tr_coeff[], double swc[])
void grass_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void shrub_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void tree_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void forb_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void pot_soil_evap (double *bserate, unsigned int nelyrs, double ecoeff[], double totagb, double fbse, double petday, double shift, double shape, double inflec, double range, double width[], double swc[], double Es_param_limit)
void pot_soil_evap_bs (double *bserate, unsigned int nelyrs, double ecoeff[], double petday, double shift, double shape, double inflec, double range, double width[], double swc[])
void pot_transp (double *bstrate, double swpavg, double biolive, double biodead, double fbst, double petday, double swp_shift, double swp_shape, double swp_inflec, double swp_range, double shade_scale, double shade_deadmax, double shade_xinflex, double shade_slope, double shade_yinflex, double shade_range)
double watrate (double swp, double petday, double shift, double shape, double inflec, double range)
void evap_litter_veg_surfaceWater (double *cwlit, double *cwstcr, double *standingWater, double *wevap, double *aet, double petday)
void evap_fromSurface (double *water_pool, double *evap_rate, double *aet)
void remove_from_soil (double swc[], double qty[], double *aet, unsigned int nlyrs, double ecoeff[], double rate, double swcmin[])
void infiltrate_water_low (double swc[], double drain[], double *drainout, unsigned int nlyrs, double sdrainpar, double sdraindpth, double swcfc[], double width[], double swcmin[], double swcsat[], double impermeability[], double *standingWater)
void hydraulic_redistribution (double swc[], double swcwp[], double lyrRootCo[], double hydred[], unsigned int nlyrs, double maxCondroot, double swp50, double shapeCond, double scale)
void soil_temperature (double airTemp, double pet, double aet, double biomass, double swc[], double swc_sat[], double bDensity[], double width[], double oldsTemp[], double sTemp[], double surfaceTemp[2], unsigned int nlyrs, double fc[], double wp[], double bmLimiter, double t1Param1, double t1Param2, double t1Param3, double csParam1, double csParam2, double shParam, double snowdepth, double meanAirTemp, double deltaX, double theMaxDepth, unsigned int nRgr, double snow)
Macro Definition Documentation
#define FREEZING_TEMP_C -1.
Referenced by set_frozen_unfrozen().
#define FUSIONHEAT_H2O 80.
#define MAX_WINTFOR (ppt)
Referenced by tree_intercepted_water().
#define MAX_WINTLIT (blitter * .2)
Referenced by litter_intercepted_water().
#define MAX_WINTSTCR (vegcov * .1)
Referenced by forb_intercepted_water(), grass_intercepted_water(), and shrub_intercepted_water().
#define MIN_VWC_TO_FREEZE 0.13
Referenced by set_frozen_unfrozen().
#define TCORRECTION 0.02
Function Documentation
void evap_fromSurface (double * water_pool, double * evap_rate, double * aet)
Referenced by SW_Water_Flow().
void evap_litter_veg_surfaceWater (double * cwlit, double * cwstcr, double * standingWater, double * wevap, double * aet, double petday)
void forb_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
Referenced by SW_Water_Flow().
void forb_intercepted_water (double * pptleft, double * wintforb, double ppt, double vegcov, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void grass_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
calculates the fraction of water lost from bare soil
Author
SLC
Parameters
fbse the fraction of water loss from bare soil evaporation
fbst the fraction of water loss from bare soil transpiration
blivelai the live biomass leaf area index
lai_param
Referenced by SW_Water_Flow().
void grass_intercepted_water (double * pptleft, double * wintgrass, double ppt, double vegcov, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void hydraulic_redistribution (double swc[], double swcwp[], double lyrRootCo[], double hydred[], unsigned int nlyrs, double maxCondroot, double swp50, double shapeCond, double scale)
Referenced by SW_Water_Flow().
void infiltrate_water_high (double swc[], double drain[], double * drainout, double pptleft, unsigned int nlyrs, double swcfc[], double swcsat[], double impermeability[], double * standingWater)
Referenced by SW_Water_Flow().
void infiltrate_water_low (double swc[], double drain[], double * drainout, unsigned int nlyrs, double sdrainpar, double sdraindpth, double swcfc[], double width[], double swcmin[], double swcsat[], double impermeability[], double * standingWater)
Referenced by SW_Water_Flow().
void litter_intercepted_water (double * pptleft, double * wintlit, double blitter, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
double petfunc (unsigned int doy, double avgtemp, double rlat, double elev, double slope, double aspect, double reflec, double humid, double windsp, double cloudcov, double transcoeff)
Referenced by SW_Water_Flow().
void pot_soil_evap (double * bserate, unsigned int nelyrs, double ecoeff[], double totagb, double fbse, double petday, double shift, double shape, double inflec, double range, double width[], double swc[], double Es_param_limit)
Referenced by SW_Water_Flow().
void pot_soil_evap_bs (double * bserate, unsigned int nelyrs, double ecoeff[], double petday, double shift, double shape, double inflec, double range, double width[], double swc[])
Referenced by SW_Water_Flow().
void pot_transp (double * bstrate, double swpavg, double biolive, double biodead, double fbst, double petday, double swp_shift, double swp_shape, double swp_inflec, double swp_range, double shade_scale, double shade_deadmax, double shade_xinflex, double shade_slope, double shade_yinflex, double shade_range)
Referenced by SW_Water_Flow().
void remove_from_soil (double swc[], double qty[], double * aet, unsigned int nlyrs, double ecoeff[], double rate, double swcmin[])
Referenced by SW_Water_Flow().
void shrub_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
Referenced by SW_Water_Flow().
void shrub_intercepted_water (double * pptleft, double * wintshrub, double ppt, double vegcov, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void soil_temperature (double airTemp, double pet, double aet, double biomass, double swc[], double swc_sat[], double bDensity[], double width[], double oldsTemp[], double sTemp[], double surfaceTemp[2], unsigned int nlyrs, double fc[], double wp[], double bmLimiter, double t1Param1, double t1Param2, double t1Param3, double csParam1, double csParam2, double shParam, double snowdepth, double meanAirTemp, double deltaX, double theMaxDepth, unsigned int nRgr, double snow)
Referenced by SW_Water_Flow().
double svapor (double temp)
calculates the saturation vapor pressure of water
Author
SLC
Parameters
temp the average temperature for the day
Returns
svapor the saturation vapor pressure (mm of hg)
Referenced by petfunc().
void transp_weighted_avg (double * swp_avg, unsigned int n_tr_rgns, unsigned int n_layers, unsigned int tr_regions[], double tr_coeff[], double swc[])
Referenced by SW_Water_Flow().
void tree_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
Referenced by SW_Water_Flow().
void tree_intercepted_water (double * pptleft, double * wintfor, double ppt, double LAI, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
double watrate (double swp, double petday, double shift, double shape, double inflec, double range)
Referenced by pot_soil_evap(), pot_soil_evap_bs(), and pot_transp().