SOILWAT2: SW_Control.h File Reference
SW_Control.h File Reference
Functions
void SW_CTL_init_model (const char *firstfile)
void SW_CTL_main (void)
void SW_CTL_run_current_year (void)
void stat_Output_Daily_CSV_Summary (int iteration)
This function will create daily.
void stat_Output_Weekly_CSV_Summary (int iteration)
Creates weekly files.
void stat_Output_Monthly_CSV_Summary (int iteration)
Creates montly files.
void stat_Output_Yearly_CSV_Summary (int iteration)
Creates yearly files.
Function Documentation
void stat_Output_Daily_CSV_Summary (int iteration)
This function will create daily.
Creates daily files.
Creates daily files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void stat_Output_Monthly_CSV_Summary (int iteration)
Creates montly files.
Creates monthly files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void stat_Output_Weekly_CSV_Summary (int iteration)
Creates weekly files.
Creates weekly files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void stat_Output_Yearly_CSV_Summary (int iteration)
Creates yearly files.
Creates yearly files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void SW_CTL_init_model (const char * firstfile)
Referenced by main().
void SW_CTL_main (void)
Referenced by main().
void SW_CTL_run_current_year (void)
Referenced by SW_CTL_main().