SOILWAT2: SW_Model.c File Reference
SW_Model.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "generic.h"
#include "filefuncs.h"
#include "rands.h"
#include "Times.h"
#include "SW_Defines.h"
#include "SW_Files.h"
#include "SW_Weather.h"
#include "SW_Site.h"
#include "SW_SoilWater.h"
#include "SW_Times.h"
#include "SW_Model.h"
Functions
void SW_MDL_construct (void)
void SW_MDL_read (void)
void SW_MDL_new_year ()
void SW_MDL_new_day (void)
Variables
SW_SITE SW_Site
SW_MODEL SW_Model
Function Documentation
void SW_MDL_construct (void)
Referenced by SW_CTL_init_model().
void SW_MDL_new_day (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_MDL_new_year (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_MDL_read (void)
Referenced by stat_Output_Yearly_CSV_Summary().
Variable Documentation
SW_MODEL SW_Model
Referenced by SW_MDL_construct(), SW_MDL_new_year(), SW_MDL_read(), and SW_OUT_write_today().
SW_SITE SW_Site