SOILWAT2: SW_Flow_lib.c File Reference
SW_Flow_lib.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "generic.h"
#include "SW_Defines.h"
#include "SW_Flow_lib.h"
#include "SW_Flow_subs.h"
#include "Times.h"
Functions
void grass_intercepted_water (double *pptleft, double *wintgrass, double ppt, double vegcov, double scale, double a, double b, double c, double d)
void shrub_intercepted_water (double *pptleft, double *wintshrub, double ppt, double vegcov, double scale, double a, double b, double c, double d)
void tree_intercepted_water (double *pptleft, double *wintfor, double ppt, double LAI, double scale, double a, double b, double c, double d)
void forb_intercepted_water (double *pptleft, double *wintforb, double ppt, double vegcov, double scale, double a, double b, double c, double d)
void litter_intercepted_water (double *pptleft, double *wintlit, double blitter, double scale, double a, double b, double c, double d)
void infiltrate_water_high (double swc[], double drain[], double *drainout, double pptleft, unsigned int nlyrs, double swcfc[], double swcsat[], double impermeability[], double *standingWater)
double petfunc (unsigned int doy, double avgtemp, double rlat, double elev, double slope, double aspect, double reflec, double humid, double windsp, double cloudcov, double transcoeff)
double svapor (double temp)
void transp_weighted_avg (double *swp_avg, unsigned int n_tr_rgns, unsigned int n_layers, unsigned int tr_regions[], double tr_coeff[], double swc[])
void grass_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void shrub_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void tree_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void forb_EsT_partitioning (double *fbse, double *fbst, double blivelai, double lai_param)
void pot_soil_evap (double *bserate, unsigned int nelyrs, double ecoeff[], double totagb, double fbse, double petday, double shift, double shape, double inflec, double range, double width[], double swc[], double Es_param_limit)
void pot_soil_evap_bs (double *bserate, unsigned int nelyrs, double ecoeff[], double petday, double shift, double shape, double inflec, double range, double width[], double swc[])
void pot_transp (double *bstrate, double swpavg, double biolive, double biodead, double fbst, double petday, double swp_shift, double swp_shape, double swp_inflec, double swp_range, double shade_scale, double shade_deadmax, double shade_xinflex, double shade_slope, double shade_yinflex, double shade_range)
double watrate (double swp, double petday, double shift, double shape, double inflec, double range)
void evap_fromSurface (double *water_pool, double *evap_rate, double *aet)
void remove_from_soil (double swc[], double qty[], double *aet, unsigned int nlyrs, double coeff[], double rate, double swcmin[])
void infiltrate_water_low (double swc[], double drain[], double *drainout, unsigned int nlyrs, double sdrainpar, double sdraindpth, double swcfc[], double width[], double swcmin[], double swcsat[], double impermeability[], double *standingWater)
void hydraulic_redistribution (double swc[], double swcwp[], double lyrRootCo[], double hydred[], unsigned int nlyrs, double maxCondroot, double swp50, double shapeCond, double scale)
void lyrTemp_to_lyrSoil_temperature (double cor[MAX_ST_RGR+1][MAX_LAYERS+1], unsigned int nlyrTemp, double depth_Temp[], double sTempR[], unsigned int nlyrSoil, double depth_Soil[], double width_Soil[], double sTemp[])
void lyrSoil_to_lyrTemp_temperature (unsigned int nlyrSoil, double depth_Soil[], double sTemp[], double endTemp, unsigned int nlyrTemp, double depth_Temp[], double maxTempDepth, double sTempR[])
void lyrSoil_to_lyrTemp (double cor[MAX_ST_RGR+1][MAX_LAYERS+1], unsigned int nlyrSoil, double width_Soil[], double var[], unsigned int nlyrTemp, double width_Temp, double res[])
double surface_temperature_under_snow (double airTempAvg, double snow)
void soil_temperature_init (double bDensity[], double width[], double surfaceTemp, double oldsTemp[], double meanAirTemp, unsigned int nlyrs, double fc[], double wp[], double deltaX, double theMaxDepth, unsigned int nRgr)
void set_frozen_unfrozen (unsigned int nlyrs, double sTemp[], double swc[], double swc_sat[], double width[])
unsigned int adjust_Tsoil_by_freezing_and_thawing (double oldsTemp[], double sTemp[], double shParam, unsigned int nlyrs, double vwc[], double bDensity[])
void endCalculations ()
void soil_temperature (double airTemp, double pet, double aet, double biomass, double swc[], double swc_sat[], double bDensity[], double width[], double oldsTemp[], double sTemp[], double surfaceTemp[2], unsigned int nlyrs, double fc[], double wp[], double bmLimiter, double t1Param1, double t1Param2, double t1Param3, double csParam1, double csParam2, double shParam, double snowdepth, double meanAirTemp, double deltaX, double theMaxDepth, unsigned int nRgr, double snow)
Variables
SW_SITE SW_Site
SW_SOILWAT SW_Soilwat
unsigned int soil_temp_error
unsigned int soil_temp_init
unsigned int fusion_pool_init
Function Documentation
unsigned int adjust_Tsoil_by_freezing_and_thawing (double oldsTemp[], double sTemp[], double shParam, unsigned int nlyrs, double vwc[], double bDensity[])
Referenced by soil_temperature().
void endCalculations ()
void evap_fromSurface (double * water_pool, double * evap_rate, double * aet)
Referenced by SW_Water_Flow().
void forb_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
Referenced by SW_Water_Flow().
void forb_intercepted_water (double * pptleft, double * wintforb, double ppt, double vegcov, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void grass_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
calculates the fraction of water lost from bare soil
Author
SLC
Parameters
fbse the fraction of water loss from bare soil evaporation
fbst the fraction of water loss from bare soil transpiration
blivelai the live biomass leaf area index
lai_param
Referenced by SW_Water_Flow().
void grass_intercepted_water (double * pptleft, double * wintgrass, double ppt, double vegcov, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void hydraulic_redistribution (double swc[], double swcwp[], double lyrRootCo[], double hydred[], unsigned int nlyrs, double maxCondroot, double swp50, double shapeCond, double scale)
Referenced by SW_Water_Flow().
void infiltrate_water_high (double swc[], double drain[], double * drainout, double pptleft, unsigned int nlyrs, double swcfc[], double swcsat[], double impermeability[], double * standingWater)
Referenced by SW_Water_Flow().
void infiltrate_water_low (double swc[], double drain[], double * drainout, unsigned int nlyrs, double sdrainpar, double sdraindpth, double swcfc[], double width[], double swcmin[], double swcsat[], double impermeability[], double * standingWater)
Referenced by SW_Water_Flow().
void litter_intercepted_water (double * pptleft, double * wintlit, double blitter, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void lyrSoil_to_lyrTemp (double cor[MAX_ST_RGR+1][MAX_LAYERS+1], unsigned int nlyrSoil, double width_Soil[], double var[], unsigned int nlyrTemp, double width_Temp, double res[])
Referenced by soil_temperature(), and soil_temperature_init().
void lyrSoil_to_lyrTemp_temperature (unsigned int nlyrSoil, double depth_Soil[], double sTemp[], double endTemp, unsigned int nlyrTemp, double depth_Temp[], double maxTempDepth, double sTempR[])
Referenced by soil_temperature(), and soil_temperature_init().
void lyrTemp_to_lyrSoil_temperature (double cor[MAX_ST_RGR+1][MAX_LAYERS+1], unsigned int nlyrTemp, double depth_Temp[], double sTempR[], unsigned int nlyrSoil, double depth_Soil[], double width_Soil[], double sTemp[])
Referenced by soil_temperature().
double petfunc (unsigned int doy, double avgtemp, double rlat, double elev, double slope, double aspect, double reflec, double humid, double windsp, double cloudcov, double transcoeff)
Referenced by SW_Water_Flow().
void pot_soil_evap (double * bserate, unsigned int nelyrs, double ecoeff[], double totagb, double fbse, double petday, double shift, double shape, double inflec, double range, double width[], double swc[], double Es_param_limit)
Referenced by SW_Water_Flow().
void pot_soil_evap_bs (double * bserate, unsigned int nelyrs, double ecoeff[], double petday, double shift, double shape, double inflec, double range, double width[], double swc[])
Referenced by SW_Water_Flow().
void pot_transp (double * bstrate, double swpavg, double biolive, double biodead, double fbst, double petday, double swp_shift, double swp_shape, double swp_inflec, double swp_range, double shade_scale, double shade_deadmax, double shade_xinflex, double shade_slope, double shade_yinflex, double shade_range)
Referenced by SW_Water_Flow().
void remove_from_soil (double swc[], double qty[], double * aet, unsigned int nlyrs, double coeff[], double rate, double swcmin[])
Referenced by SW_Water_Flow().
void set_frozen_unfrozen (unsigned int nlyrs, double sTemp[], double swc[], double swc_sat[], double width[])
Referenced by soil_temperature().
void shrub_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
Referenced by SW_Water_Flow().
void shrub_intercepted_water (double * pptleft, double * wintshrub, double ppt, double vegcov, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
void soil_temperature (double airTemp, double pet, double aet, double biomass, double swc[], double swc_sat[], double bDensity[], double width[], double oldsTemp[], double sTemp[], double surfaceTemp[2], unsigned int nlyrs, double fc[], double wp[], double bmLimiter, double t1Param1, double t1Param2, double t1Param3, double csParam1, double csParam2, double shParam, double snowdepth, double meanAirTemp, double deltaX, double theMaxDepth, unsigned int nRgr, double snow)
Referenced by SW_Water_Flow().
void soil_temperature_init (double bDensity[], double width[], double surfaceTemp, double oldsTemp[], double meanAirTemp, unsigned int nlyrs, double fc[], double wp[], double deltaX, double theMaxDepth, unsigned int nRgr)
Referenced by soil_temperature().
double surface_temperature_under_snow (double airTempAvg, double snow)
Determines the average temperature of the soil surface under snow. Based upon Parton et al. 1998. Equations 5 & 6.
Parameters
airTempAvg the average air temperature of the area, in Celsius
snow the snow-water-equivalent of the area, in cm
Returns
the modified, average temperature of the soil surface
the effect of snow based on swe
the average temeperature of the soil surface
Parton et al. 1998. Equation 6.
Parton et al. 1998. Equation 5.
Referenced by soil_temperature().
double svapor (double temp)
calculates the saturation vapor pressure of water
Author
SLC
Parameters
temp the average temperature for the day
Returns
svapor the saturation vapor pressure (mm of hg)
Referenced by petfunc().
void transp_weighted_avg (double * swp_avg, unsigned int n_tr_rgns, unsigned int n_layers, unsigned int tr_regions[], double tr_coeff[], double swc[])
Referenced by SW_Water_Flow().
void tree_EsT_partitioning (double * fbse, double * fbst, double blivelai, double lai_param)
Referenced by SW_Water_Flow().
void tree_intercepted_water (double * pptleft, double * wintfor, double ppt, double LAI, double scale, double a, double b, double c, double d)
Referenced by SW_Water_Flow().
double watrate (double swp, double petday, double shift, double shape, double inflec, double range)
Referenced by pot_soil_evap(), pot_soil_evap_bs(), and pot_transp().
Variable Documentation
unsigned int fusion_pool_init
Referenced by adjust_Tsoil_by_freezing_and_thawing(), and SW_FLW_construct().
unsigned int soil_temp_error
Referenced by endCalculations(), soil_temperature(), soil_temperature_init(), and SW_FLW_construct().
unsigned int soil_temp_init
Referenced by soil_temperature(), soil_temperature_init(), and SW_FLW_construct().
SW_SITE SW_Site
SW_SOILWAT SW_Soilwat