SOILWAT2: SW_SoilWater.h File Reference
SW_SoilWater.h File Reference
#include "generic.h"
#include "SW_Defines.h"
#include "SW_Times.h"
#include "SW_Site.h"
Data Structures
struct SW_SOILWAT_HIST
struct SW_SOILWAT_OUTPUTS
struct SW_SOILWAT
Enumerations
enum SW_AdjustMethods { SW_Adjust_Avg = 1, SW_Adjust_StdErr }
Functions
void SW_SWC_construct (void)
void SW_SWC_new_year (void)
void SW_SWC_read (void)
void SW_SWC_water_flow (void)
void SW_SWC_adjust_swc (TimeInt doy)
void SW_SWC_adjust_snow (RealD temp_min, RealD temp_max, RealD ppt, RealD *rain, RealD *snow, RealD *snowmelt, RealD *snowloss)
RealD SW_SnowDepth (RealD SWE, RealD snowdensity)
void SW_SWC_end_day (void)
RealD SW_SWCbulk2SWPmatric (RealD fractionGravel, RealD swcBulk, LyrIndex n)
RealD SW_SWPmatric2VWCBulk (RealD fractionGravel, RealD swpMatric, LyrIndex n)
RealD SW_VWCBulkRes (RealD fractionGravel, RealD sand, RealD clay, RealD porosity)
Enumeration Type Documentation
enum SW_AdjustMethods
Enumerator
SW_Adjust_Avg
SW_Adjust_StdErr
Function Documentation
RealD SW_SnowDepth (RealD SWE, RealD snowdensity)
Referenced by SW_Water_Flow().
void SW_SWC_adjust_snow (RealD temp_min, RealD temp_max, RealD ppt, RealD * rain, RealD * snow, RealD * snowmelt, RealD * snowloss)
Referenced by SW_WTH_new_day().
void SW_SWC_adjust_swc (TimeInt doy)
Referenced by SW_SWC_water_flow().
void SW_SWC_construct (void)
Referenced by SW_CTL_init_model().
void SW_SWC_end_day (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_SWC_new_year (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_SWC_read (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_SWC_water_flow (void)
Referenced by SW_CTL_run_current_year().
RealD SW_SWCbulk2SWPmatric (RealD fractionGravel, RealD swcBulk, LyrIndex n)
Referenced by SW_OUT_write_today(), SW_SIT_clear_layers(), and SWCbulk2SWPmatric().
RealD SW_SWPmatric2VWCBulk (RealD fractionGravel, RealD swpMatric, LyrIndex n)
Referenced by init_site_info(), SW_SIT_read(), and SW_VES_checkestab().
RealD SW_VWCBulkRes (RealD fractionGravel, RealD sand, RealD clay, RealD porosity)
Referenced by init_site_info().