SOILWAT2: SW_VegEstab.h File Reference
SW_VegEstab.h File Reference
#include "SW_Defines.h"
#include "SW_Times.h"
Data Structures
struct SW_VEGESTAB_INFO
struct SW_VEGESTAB_OUTPUTS
struct SW_VEGESTAB
Macros
#define SW_GERM_BARS 0
#define SW_ESTAB_BARS 1
Functions
void SW_VES_read (void)
void SW_VES_construct (void)
void SW_VES_clear (void)
void SW_VES_init (void)
void SW_VES_checkestab (void)
void SW_VES_new_year (void)
Macro Definition Documentation
#define SW_ESTAB_BARS 1
Referenced by SW_VES_checkestab().
#define SW_GERM_BARS 0
Referenced by SW_VES_checkestab().
Function Documentation
void SW_VES_checkestab (void)
Referenced by SW_CTL_run_current_year().
void SW_VES_clear (void)
void SW_VES_construct (void)
Referenced by SW_CTL_init_model().
void SW_VES_init (void)
void SW_VES_new_year (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_VES_read (void)
Referenced by stat_Output_Yearly_CSV_Summary().