SOILWAT2: SW_Output.c File Reference
SW_Output.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "generic.h"
#include "filefuncs.h"
#include "myMemory.h"
#include "Times.h"
#include "SW_Defines.h"
#include "SW_Files.h"
#include "SW_Model.h"
#include "SW_Site.h"
#include "SW_SoilWater.h"
#include "SW_Times.h"
#include "SW_Output.h"
#include "SW_Weather.h"
#include "SW_VegEstab.h"
#include "SW_VegProd.h"
Macros
#define OUTSTRLEN 3000 /* max output string length: in get_transp: 4*every soil layer with 14 chars */
Functions
void populate_output_values (char *reg_file_array, char *soil_file_array, int output_var, int year_out)
Populates arrays with output in correct format.
void create_col_headers (int outFileTimestep, FILE *regular_file, FILE *soil_file)
Creates column headers for output files.
void SW_OUT_construct (void)
void SW_OUT_new_year (void)
void SW_OUT_read (void)
void SW_OUT_close_files (void)
void SW_OUT_flush (void)
void SW_OUT_sum_today (ObjType otyp)
void SW_OUT_write_today (void)
Variables
SW_SITE SW_Site
SW_SOILWAT SW_Soilwat
SW_MODEL SW_Model
SW_WEATHER SW_Weather
SW_VEGESTAB SW_VegEstab
SW_VEGPROD SW_VegProd
Bool EchoInits
SW_OUTPUT SW_Output [SW_OUTNKEYS]
SW_OUTPUT SW_Output_Files
int col_status_dy = 0
int col_status_wk = 0
int col_status_mo = 0
int col_status_yr = 0
int lastMonth = 0
int lastWeek = 0
int finalValue = 0
Macro Definition Documentation
#define OUTSTRLEN 3000 /* max output string length: in get_transp: 4*every soil layer with 14 chars */
Referenced by SW_OUT_write_today().
Function Documentation
void create_col_headers (int outFileTimestep, FILE * regular_file, FILE * soil_file)
Creates column headers for output files.
create_col_headers is called only once for each set of output files and it goes through all values and if the value is defined to be used it creates the header in the output file
Parameters
outFileTimestep. timeperiod so it can write headers to correct output file.
regular_file. name of file.
soil_file. name of file.
Returns
void.
Referenced by SW_OUT_write_today().
void populate_output_values (char * reg_file_array, char * soil_file_array, int output_var, int year_out)
Populates arrays with output in correct format.
populate_output_values is called for all of the variables for each timeperiod and these values are parsed to the proper format defined in the .in file for output file type.
Parameters
reg_file_array. stores output for non-soil variables.
soil_file_array. stores output for variables with layers.
output_var. Tells function which value its using.
year_out. Tells us which timeperiod we are using for display purposes.
Returns
void.
Referenced by SW_OUT_write_today().
void SW_OUT_close_files (void)
Referenced by SW_CTL_main().
void SW_OUT_construct (void)
Referenced by SW_CTL_init_model().
void SW_OUT_flush (void)
Referenced by SW_CTL_run_current_year().
void SW_OUT_new_year (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_OUT_read (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_OUT_sum_today (ObjType otyp)
Referenced by stat_Output_Yearly_CSV_Summary(), and SW_OUT_flush().
void SW_OUT_write_today (void)
Referenced by stat_Output_Yearly_CSV_Summary(), and SW_OUT_flush().
Variable Documentation
int col_status_dy = 0
Referenced by SW_OUT_write_today().
int col_status_mo = 0
Referenced by SW_OUT_write_today().
int col_status_wk = 0
Referenced by SW_OUT_write_today().
int col_status_yr = 0
Referenced by SW_OUT_write_today().
Bool EchoInits
Referenced by SW_OUT_read().
int finalValue = 0
Referenced by SW_OUT_write_today().
int lastMonth = 0
Referenced by SW_OUT_write_today().
int lastWeek = 0
Referenced by SW_OUT_write_today().
SW_MODEL SW_Model
Referenced by SW_OUT_write_today().
SW_OUTPUT SW_Output[SW_OUTNKEYS]
SW_OUTPUT SW_Output_Files
SW_SITE SW_Site
SW_SOILWAT SW_Soilwat
Referenced by SW_OUT_sum_today(), and SW_OUT_write_today().
SW_VEGESTAB SW_VegEstab
Referenced by SW_OUT_write_today(), and SW_VES_checkestab().
SW_VEGPROD SW_VegProd
SW_WEATHER SW_Weather
Referenced by SW_OUT_sum_today(), and SW_OUT_write_today().