SOILWAT2: SW_Control.c File Reference
SW_Control.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "generic.h"
#include "filefuncs.h"
#include "rands.h"
#include "SW_Defines.h"
#include "SW_Files.h"
#include "SW_Control.h"
#include "SW_Model.h"
#include "SW_Output.h"
#include "SW_Site.h"
#include "SW_SoilWater.h"
#include "SW_VegEstab.h"
#include "SW_VegProd.h"
#include "SW_Weather.h"
Functions
void SW_FLW_construct (void)
void SW_CTL_main (void)
void SW_CTL_init_model (const char *firstfile)
void SW_CTL_run_current_year (void)
void stat_Output_Daily_CSV_Summary (int iteration)
This function will create daily.
void stat_Output_Weekly_CSV_Summary (int iteration)
Creates weekly files.
void stat_Output_Monthly_CSV_Summary (int iteration)
Creates montly files.
void stat_Output_Yearly_CSV_Summary (int iteration)
Creates yearly files.
Variables
SW_MODEL SW_Model
SW_VEGESTAB SW_VegEstab
SW_VEGPROD SW_VegProd
SW_OUTPUT SW_Output_Files
char * InFiles [SW_NFILES]
Function Documentation
void stat_Output_Daily_CSV_Summary (int iteration)
This function will create daily.
Creates daily files.
Creates daily files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void stat_Output_Monthly_CSV_Summary (int iteration)
Creates montly files.
Creates monthly files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void stat_Output_Weekly_CSV_Summary (int iteration)
Creates weekly files.
Creates weekly files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void stat_Output_Yearly_CSV_Summary (int iteration)
Creates yearly files.
Creates yearly files for SOILWAT standalone and for STEPWAT depending on defined flags for STEPWAT if -i flag is used it creates file for each iteration naming file based on iteration
Parameters
iteration. Current iteration for file name if -i flag used in STEPWAT
Referenced by SW_OUT_read().
void SW_CTL_init_model (const char * firstfile)
Referenced by main().
void SW_CTL_main (void)
Referenced by main().
void SW_CTL_run_current_year (void)
Referenced by SW_CTL_main().
void SW_FLW_construct (void)
Referenced by SW_CTL_init_model().
Variable Documentation
char* InFiles[SW_NFILES]
Referenced by SW_F_construct(), SW_F_name(), SW_F_read(), and SW_OutputPrefix().
SW_MODEL SW_Model
SW_OUTPUT SW_Output_Files
SW_VEGESTAB SW_VegEstab
SW_VEGPROD SW_VegProd