SOILWAT2: SW_SoilWater.c File Reference
SW_SoilWater.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "generic.h"
#include "filefuncs.h"
#include "myMemory.h"
#include "SW_Defines.h"
#include "SW_Files.h"
#include "SW_Model.h"
#include "SW_Site.h"
#include "SW_SoilWater.h"
#include "SW_Output.h"
Functions
void SW_Water_Flow (void)
void SW_SWC_construct (void)
void SW_SWC_water_flow (void)
void SW_SWC_end_day (void)
void SW_SWC_new_year (void)
void SW_SWC_read (void)
void SW_SWC_adjust_swc (TimeInt doy)
void SW_SWC_adjust_snow (RealD temp_min, RealD temp_max, RealD ppt, RealD *rain, RealD *snow, RealD *snowmelt, RealD *snowloss)
RealD SW_SnowDepth (RealD SWE, RealD snowdensity)
RealD SW_SWCbulk2SWPmatric (RealD fractionGravel, RealD swcBulk, LyrIndex n)
RealD SW_SWPmatric2VWCBulk (RealD fractionGravel, RealD swpMatric, LyrIndex n)
RealD SW_VWCBulkRes (RealD fractionGravel, RealD sand, RealD clay, RealD porosity)
Variables
SW_MODEL SW_Model
SW_SITE SW_Site
SW_SOILWAT SW_Soilwat
Function Documentation
RealD SW_SnowDepth (RealD SWE, RealD snowdensity)
Referenced by SW_Water_Flow().
void SW_SWC_adjust_snow (RealD temp_min, RealD temp_max, RealD ppt, RealD * rain, RealD * snow, RealD * snowmelt, RealD * snowloss)
Referenced by SW_WTH_new_day().
void SW_SWC_adjust_swc (TimeInt doy)
Referenced by SW_SWC_water_flow().
void SW_SWC_construct (void)
Referenced by SW_CTL_init_model().
void SW_SWC_end_day (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_SWC_new_year (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_SWC_read (void)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_SWC_water_flow (void)
Referenced by SW_CTL_run_current_year().
RealD SW_SWCbulk2SWPmatric (RealD fractionGravel, RealD swcBulk, LyrIndex n)
Referenced by SW_OUT_write_today(), SW_SIT_clear_layers(), and SWCbulk2SWPmatric().
RealD SW_SWPmatric2VWCBulk (RealD fractionGravel, RealD swpMatric, LyrIndex n)
Referenced by init_site_info(), SW_SIT_read(), and SW_VES_checkestab().
RealD SW_VWCBulkRes (RealD fractionGravel, RealD sand, RealD clay, RealD porosity)
Referenced by init_site_info().
void SW_Water_Flow (void)
Referenced by SW_SWC_water_flow().
Variable Documentation
SW_MODEL SW_Model
SW_SITE SW_Site
SW_SOILWAT SW_Soilwat
Referenced by SW_OUT_sum_today(), SW_OUT_write_today(), SW_SWC_adjust_swc(), SW_SWC_end_day(), SW_SWC_read(), and SW_VES_checkestab().