SOILWAT2: SW_Files.h File Reference
SW_Files.h File Reference
Macros
#define SW_NFILES 23
Enumerations
enum SW_FileIndex {
eNoFile = -1, eFirst = 0, eModel, eLog,
eSite, eLayers, eWeather, eMarkovProb,
eMarkovCov, eSky, eVegProd, eVegEstab,
eSoilwat, eOutput, eOutputDaily, eOutputWeekly,
eOutputMonthly, eOutputYearly, eOutputDaily_soil, eOutputWeekly_soil,
eOutputMonthly_soil, eOutputYearly_soil, eEndFile
}
Functions
void SW_F_read (const char *s)
char * SW_F_name (SW_FileIndex i)
void SW_F_construct (const char *firstfile)
void SW_WeatherPrefix (char prefix[])
void SW_OutputPrefix (char prefix[])
void SW_CSV_F_INIT (const char *s)
Macro Definition Documentation
#define SW_NFILES 23
Referenced by SW_F_construct(), and SW_F_read().
Enumeration Type Documentation
enum SW_FileIndex
Enumerator
eNoFile
eFirst
eModel
eLog
eSite
eLayers
eWeather
eMarkovProb
eMarkovCov
eSky
eVegProd
eVegEstab
eSoilwat
eOutput
eOutputDaily
eOutputWeekly
eOutputMonthly
eOutputYearly
eOutputDaily_soil
eOutputWeekly_soil
eOutputMonthly_soil
eOutputYearly_soil
eEndFile
Function Documentation
void SW_CSV_F_INIT (const char * s)
Referenced by SW_F_read().
void SW_F_construct (const char * firstfile)
Referenced by SW_CTL_init_model(), and SW_F_construct().
char* SW_F_name (SW_FileIndex i)
Referenced by init_site_info(), stat_Output_Daily_CSV_Summary(), stat_Output_Monthly_CSV_Summary(), stat_Output_Weekly_CSV_Summary(), stat_Output_Yearly_CSV_Summary(), SW_F_read(), SW_MDL_read(), SW_MKV_read_cov(), SW_MKV_read_prob(), SW_OUT_read(), SW_SIT_clear_layers(), SW_SIT_read(), SW_SKY_read(), SW_SWC_adjust_swc(), SW_SWC_read(), SW_VES_read(), SW_VPD_read(), and SW_WTH_read().
void SW_F_read (const char * s)
Referenced by stat_Output_Yearly_CSV_Summary().
void SW_OutputPrefix (char prefix[])
void SW_WeatherPrefix (char prefix[])
Referenced by SW_WTH_read().