SOILWAT2: Times.h File Reference
Times.h File Reference
#include <time.h>
#include "generic.h"
Macros
#define MAX_MONTHS 12
#define MAX_WEEKS 53
#define MAX_DAYS 366
#define WKDAYS 7
Typedefs
typedef unsigned int TimeInt
Enumerations
enum Months {
Jan, Feb, Mar, Apr,
May, Jun, Jul, Aug,
Sep, Oct, Nov, Dec,
NoMonth
}
Functions
void Time_init (void)
void Time_now (void)
void Time_new_year (TimeInt year)
void Time_next_day (void)
void Time_set_year (TimeInt year)
void Time_set_doy (const TimeInt doy)
void Time_set_mday (const TimeInt day)
void Time_set_month (const TimeInt mon)
time_t Time_timestamp (void)
time_t Time_timestamp_now (void)
TimeInt Time_days_in_month (Months month)
TimeInt Time_lastDOY (void)
char * Time_printtime (void)
char * Time_daynmshort (void)
char * Time_daynmshort_d (const TimeInt doy)
char * Time_daynmshort_dm (const TimeInt mday, const TimeInt mon)
char * Time_daynmlong (void)
char * Time_daynmlong_d (const TimeInt doy)
char * Time_daynmlong_dm (const TimeInt mday, const TimeInt mon)
TimeInt Time_get_year (void)
TimeInt Time_get_doy (void)
TimeInt Time_get_month (void)
TimeInt Time_get_week (void)
TimeInt Time_get_mday (void)
TimeInt Time_get_hour (void)
TimeInt Time_get_mins (void)
TimeInt Time_get_secs (void)
TimeInt Time_get_lastdoy (void)
TimeInt Time_get_lastdoy_y (TimeInt year)
TimeInt doy2month (const TimeInt doy)
TimeInt doy2mday (const TimeInt doy)
TimeInt doy2week (TimeInt doy)
TimeInt yearto4digit (TimeInt yr)
Bool isleapyear_now (void)
Bool isleapyear (const TimeInt year)
void interpolate_monthlyValues (double monthlyValues[], double dailyValues[])
Macro Definition Documentation
#define MAX_DAYS 366
Referenced by interpolate_monthlyValues(), SW_MKV_construct(), SW_MKV_read_prob(), and SW_VPD_init().
#define MAX_MONTHS 12
Referenced by SW_SKY_init(), SW_WTH_read(), and Time_init().
#define MAX_WEEKS 53
Referenced by SW_MKV_read_cov().
#define WKDAYS 7
Referenced by doy2week(), and SW_OUT_write_today().
Typedef Documentation
typedef unsigned int TimeInt
Enumeration Type Documentation
enum Months
Enumerator
Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec
NoMonth
Function Documentation
TimeInt doy2mday (const TimeInt doy)
Referenced by interpolate_monthlyValues(), Time_daynmlong_d(), Time_daynmshort_d(), Time_set_doy(), and Time_set_year().
TimeInt doy2month (const TimeInt doy)
Referenced by doy2mday(), interpolate_monthlyValues(), SW_MDL_new_day(), Time_daynmlong_d(), Time_daynmshort_d(), Time_set_doy(), and Time_set_year().
TimeInt doy2week (TimeInt doy)
Referenced by SW_MDL_new_day(), and Time_get_week().
void interpolate_monthlyValues (double monthlyValues[], double dailyValues[])
Referenced by SW_SKY_init(), and SW_VPD_init().
Bool isleapyear (const TimeInt year)
Referenced by isleapyear_now(), SW_WTH_read(), and Time_get_lastdoy_y().
Bool isleapyear_now (void)
Referenced by interpolate_monthlyValues().
char* Time_daynmlong (void)
char* Time_daynmlong_d (const TimeInt doy)
char* Time_daynmlong_dm (const TimeInt mday, const TimeInt mon)
char* Time_daynmshort (void)
char* Time_daynmshort_d (const TimeInt doy)
char* Time_daynmshort_dm (const TimeInt mday, const TimeInt mon)
TimeInt Time_days_in_month (Months month)
Referenced by SW_OUT_write_today().
TimeInt Time_get_doy (void)
TimeInt Time_get_hour (void)
TimeInt Time_get_lastdoy (void)
TimeInt Time_get_lastdoy_y (TimeInt year)
Referenced by SW_MDL_read(), and SW_WTH_read().
TimeInt Time_get_mday (void)
TimeInt Time_get_mins (void)
TimeInt Time_get_month (void)
TimeInt Time_get_secs (void)
TimeInt Time_get_week (void)
TimeInt Time_get_year (void)
void Time_init (void)
Referenced by SW_MDL_construct().
TimeInt Time_lastDOY (void)
Referenced by SW_MDL_new_year().
void Time_new_year (TimeInt year)
Referenced by SW_MDL_new_year().
void Time_next_day (void)
void Time_now (void)
Referenced by Time_init().
char* Time_printtime (void)
void Time_set_doy (const TimeInt doy)
Referenced by Time_new_year(), and Time_next_day().
void Time_set_mday (const TimeInt day)
void Time_set_month (const TimeInt mon)
void Time_set_year (TimeInt year)
time_t Time_timestamp (void)
time_t Time_timestamp_now (void)
TimeInt yearto4digit (TimeInt yr)
Referenced by isleapyear(), SW_MDL_read(), SW_SWC_read(), Time_new_year(), and Time_set_year().