SOILWAT2: filefuncs.h File Reference
filefuncs.h File Reference
#include "generic.h"
Macros
#define FILEFUNCS_H
Functions
FILE * OpenFile (const char *, const char *)
void CloseFile (FILE **)
Bool GetALine (FILE *f, char buf[])
char * DirName (const char *p)
const char * BaseName (const char *p)
Bool FileExists (const char *f)
Bool DirExists (const char *d)
Bool ChDir (const char *d)
Bool MkDir (const char *d)
Bool RemoveFiles (const char *fspec)
Variables
char inbuf []
Macro Definition Documentation
FILEFUNCS_H
#define FILEFUNCS_H
Function Documentation
BaseName()
const char* BaseName (const char * p)
Referenced by getfiles().
ChDir()
Bool ChDir (const char * d)
CloseFile()
void CloseFile (FILE **)
DirExists()
Bool DirExists (const char * d)
Referenced by MkDir().
DirName()
char* DirName (const char * p)
Referenced by getfiles(), and RemoveFiles().
FileExists()
Bool FileExists (const char * f)
GetALine()
Bool GetALine (FILE * f, char buf[])
MkDir()
Bool MkDir (const char * d)
OpenFile()
FILE* OpenFile (const char * , const char *)
RemoveFiles()
Bool RemoveFiles (const char * fspec)
Variable Documentation
inbuf
char inbuf[]