SOILWAT2: filefuncs.c File Reference
filefuncs.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#include <unistd.h>
#include "filefuncs.h"
#include "myMemory.h"
Functions
char ** getfiles (const char *fspec, int *nfound)
Bool GetALine (FILE *f, char buf[])
char * DirName (const char *p)
const char * BaseName (const char *p)
FILE * OpenFile (const char *name, const char *mode)
void CloseFile (FILE **f)
Bool FileExists (const char *name)
Bool DirExists (const char *dname)
Bool ChDir (const char *dname)
Bool MkDir (const char *dname)
Bool RemoveFiles (const char *fspec)
Function Documentation
const char* BaseName (const char * p)
Referenced by getfiles().
Bool ChDir (const char * dname)
Referenced by init_args().
void CloseFile (FILE ** f)
Referenced by main(), SW_F_read(), SW_MDL_read(), SW_MKV_read_cov(), SW_MKV_read_prob(), SW_OUT_close_files(), SW_OUT_read(), SW_SIT_read(), SW_SKY_read(), SW_SWC_read(), SW_VES_checkestab(), SW_VES_read(), SW_VPD_read(), and SW_WTH_read().
Bool DirExists (const char * dname)
Referenced by MkDir(), and SW_CSV_F_INIT().
char* DirName (const char * p)
Referenced by getfiles(), RemoveFiles(), SW_CSV_F_INIT(), and SW_F_construct().
Bool FileExists (const char * name)
Referenced by SW_SWC_read().
Bool GetALine (FILE * f, char buf[])
Referenced by SW_F_read(), SW_MDL_read(), SW_MKV_read_cov(), SW_MKV_read_prob(), SW_OUT_read(), SW_SIT_read(), SW_SKY_read(), SW_SWC_read(), SW_VES_checkestab(), SW_VES_read(), SW_VPD_read(), and SW_WTH_read().
char ** getfiles (const char * fspec, int * nfound)
Referenced by RemoveFiles().
Bool MkDir (const char * dname)
Referenced by SW_CSV_F_INIT().
FILE* OpenFile (const char * name, const char * mode)
Referenced by stat_Output_Daily_CSV_Summary(), stat_Output_Monthly_CSV_Summary(), stat_Output_Weekly_CSV_Summary(), stat_Output_Yearly_CSV_Summary(), SW_F_read(), SW_MDL_read(), SW_OUT_read(), SW_SIT_read(), SW_SKY_read(), SW_SWC_read(), SW_VES_checkestab(), SW_VES_read(), SW_VPD_read(), and SW_WTH_read().
Bool RemoveFiles (const char * fspec)
Referenced by SW_CSV_F_INIT().