SOILWAT2: generic.c File Reference
generic.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdarg.h>
#include "generic.h"
#include "filefuncs.h"
Functions
char * Str_TrimLeft (char *s)
char * Str_TrimLeftQ (char *s)
char * Str_TrimRight (char *s)
char * Str_ToUpper (char *s, char *r)
char * Str_ToLower (char *s, char *r)
int Str_CompareI (char *t, char *s)
void UnComment (char *s)
void LogError (FILE *fp, const int mode, const char *fmt,...)
Bool Is_LeapYear (int yr)
double interpolation (double x1, double x2, double y1, double y2, double deltaX)
void st_getBounds (unsigned int *x1, unsigned int *x2, unsigned int *equal, unsigned int size, double depth, double bounds[])
double lobfM (double xs[], double ys[], unsigned int n)
double lobfB (double xs[], double ys[], unsigned int n)
void lobf (double *m, double *b, double xs[], double ys[], unsigned int n)
Function Documentation
interpolation()
double interpolation (double x1, double x2, double y1, double y2, double deltaX)
Referenced by lyrSoil_to_lyrTemp_temperature(), and lyrTemp_to_lyrSoil_temperature().
Is_LeapYear()
Bool Is_LeapYear (int yr)
lobf()
void lobf (double * m, double * b, double xs[], double ys[], unsigned int n)
lobfB()
double lobfB (double xs[], double ys[], unsigned int n)
Referenced by lobf().
lobfM()
double lobfM (double xs[], double ys[], unsigned int n)
Referenced by lobf(), and lobfB().
LogError()
void LogError (FILE * fp, const int mode, const char * fmt, ...)
Referenced by calculate_CO2_multipliers(), Mem_Free(), Mem_Malloc(), Mem_ReAlloc(), OpenFile(), SW_CBN_construct(), SW_OUT_sum_today(), SW_SWC_adjust_swc(), SW_SWC_water_flow(), SW_SWCbulk2SWPmatric(), and water_eqn().
st_getBounds()
void st_getBounds (unsigned int * x1, unsigned int * x2, unsigned int * equal, unsigned int size, double depth, double bounds[])
Str_CompareI()
int Str_CompareI (char * t, char * s)
Str_ToLower()
char* Str_ToLower (char * s, char * r)
Str_ToUpper()
char* Str_ToUpper (char * s, char * r)
Referenced by Str_CompareI().
Str_TrimLeft()
char* Str_TrimLeft (char * s)
Str_TrimLeftQ()
char* Str_TrimLeftQ (char * s)
Str_TrimRight()
char* Str_TrimRight (char * s)
UnComment()
void UnComment (char * s)
Referenced by GetALine().