SOILWAT2: memblock.h File Reference
memblock.h File Reference
#include <stdlib.h>
#include <assert.h>
Data Structures
struct BLOCKINFO
Macros
#define bGarbage 0xCC
#define fPtrLess(pLeft, pRight) ((pLeft) < (pRight))
#define fPtrGrtr(pLeft, pRight) ((pLeft) > (pRight))
#define fPtrEqual(pLeft, pRight) ((pLeft) == (pRight))
#define fPtrLessEq(pLeft, pRight) ((pLeft) <= (pRight))
#define fPtrGrtrEq(pLeft, pRight) ((pLeft) >= (pRight))
Typedefs
typedef signed char flag
typedef struct BLOCKINFO blockinfo
Functions
flag fCreateBlockInfo (byte *pbNew, size_t sizeNew)
void FreeBlockInfo (byte *pbToFree)
void UpdateBlockInfo (byte *pbOld, byte *pbNew, size_t sizeNew)
size_t sizeofBlock (byte *pb)
void ClearMemoryRefs (void)
void NoteMemoryRef (void *pv)
void CheckMemoryRefs (void)
flag fValidPointer (void *pv, size_t size)
Macro Definition Documentation
bGarbage
#define bGarbage 0xCC
Referenced by Mem_Copy(), Mem_Free(), Mem_Malloc(), and Mem_ReAlloc().
fPtrEqual
#define fPtrEqual (pLeft, pRight) ((pLeft) == (pRight))
Referenced by Mem_Copy().
fPtrGrtr
#define fPtrGrtr (pLeft, pRight) ((pLeft) > (pRight))
Referenced by Mem_Copy().
fPtrGrtrEq
#define fPtrGrtrEq (pLeft, pRight) ((pLeft) >= (pRight))
Referenced by Mem_Copy().
fPtrLess
#define fPtrLess (pLeft, pRight) ((pLeft) < (pRight))
Referenced by Mem_Copy().
fPtrLessEq
#define fPtrLessEq (pLeft, pRight) ((pLeft) <= (pRight))
Referenced by Mem_Copy().
Typedef Documentation
blockinfo
typedef struct BLOCKINFO blockinfo
flag
typedef signed char flag
Function Documentation
CheckMemoryRefs()
void CheckMemoryRefs (void)
Referenced by Mem_Copy().
ClearMemoryRefs()
void ClearMemoryRefs (void)
Referenced by Mem_Copy().
fCreateBlockInfo()
flag fCreateBlockInfo (byte * pbNew, size_t sizeNew)
Referenced by Mem_Copy(), and Mem_Malloc().
FreeBlockInfo()
void FreeBlockInfo (byte * pbToFree)
Referenced by Mem_Copy(), and Mem_Free().
fValidPointer()
flag fValidPointer (void * pv, size_t size)
Referenced by Mem_Copy(), Mem_Free(), and Mem_Set().
NoteMemoryRef()
void NoteMemoryRef (void * pv)
Referenced by Mem_Copy().
sizeofBlock()
size_t sizeofBlock (byte * pb)
Referenced by Mem_Copy(), Mem_Free(), and Mem_ReAlloc().
UpdateBlockInfo()
void UpdateBlockInfo (byte * pbOld, byte * pbNew, size_t sizeNew)
Referenced by Mem_Copy(), and Mem_ReAlloc().