SOILWAT2: myMemory.h File Reference
myMemory.h File Reference
#include <memory.h>
#include "generic.h"
Functions
char * Str_Dup (const char *s)
void * Mem_Malloc (size_t size, const char *funcname)
void * Mem_Calloc (size_t nobjs, size_t size, const char *funcname)
void * Mem_ReAlloc (void *block, size_t sizeNew)
void Mem_Free (void *block)
void Mem_Set (void *block, byte c, size_t n)
void Mem_Copy (void *dest, const void *src, size_t n)
Function Documentation
void* Mem_Calloc (size_t nobjs, size_t size, const char * funcname)
Referenced by SW_MKV_construct(), SW_VES_checkestab(), SW_VES_read(), SW_WTH_read(), and water_eqn().
void Mem_Copy (void * dest, const void * src, size_t n)
void Mem_Free (void * block)
Referenced by Mem_ReAlloc(), RandUniList(), RemoveFiles(), SW_F_construct(), SW_F_read(), SW_OUT_construct(), and SW_SWC_construct().
void* Mem_Malloc (size_t size, const char * funcname)
Referenced by getfiles(), Mem_Calloc(), Mem_ReAlloc(), RandUniList(), and Str_Dup().
void* Mem_ReAlloc (void * block, size_t sizeNew)
Referenced by getfiles(), SW_VES_checkestab(), and water_eqn().
void Mem_Set (void * block, byte c, size_t n)
Referenced by Mem_Calloc(), and SW_VES_new_year().
char* Str_Dup (const char * s)
Referenced by getfiles(), SW_F_construct(), SW_F_read(), SW_OUT_read(), SW_SIT_read(), and SW_SWC_read().