SOILWAT2: rands.c File Reference
rands.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <time.h>
#include "generic.h"
#include "rands.h"
#include "myMemory.h"
Macros
#define BUCKETSIZE 97
Functions
void RandSeed (signed long seed)
Resets the random number seed.
double RandUni_fast (void)
Generate a uniform random variate.
double RandUni_good (void)
Generate a uniform random variate.
int RandUniRange (const long first, const long last)
Generate a random integer between two numbers.
void RandUniList (long count, long first, long last, RandListType list[])
double RandNorm (double mean, double stddev)
float genbet (float aa, float bb)
Variables
long _randseed = 0L
Macro Definition Documentation
BUCKETSIZE
#define BUCKETSIZE 97
Referenced by RandUni_fast(), and RandUni_good().
Function Documentation
genbet()
float genbet (float aa, float bb)
RandNorm()
double RandNorm (double mean, double stddev)
Referenced by SW_MKV_today().
RandSeed()
void RandSeed (signed long seed)
Resets the random number seed.
The seed is set to negative when this routine is called, so the generator routines (eg, RandUni()) can tell that it has changed. If called with seed==0, _randseed is reset from process time. '% 0xffff' is due to a bug in RandUni() that conks if seed is too large; should be removed in the near future.
Parameters
seed The seed.
cwb - 6/27/00
Referenced by SW_MDL_construct().
RandUni_fast()
double RandUni_fast (void)
Generate a uniform random variate.
"Fast" because it utilizes the system rand() but shuffles the results to make a less correlated sequence. This code is based on FUNCTION RAN0 in Press, et al., 1986, Numerical Recipes, p196, Press Syndicate, NY.
Of course, just how fast is "fast" depends on the implementation of the compiler. Some older generators may be quite simple, and so would be faster than a more complicated algorithm. Newer rand()'s are often fast and good.
cwb 18-Dec-02
Returns
double. A value between 0 and 1.
RandUni_good()
double RandUni_good (void)
Generate a uniform random variate.
Return a random number from uniform distribution. Result is between 0 and 1. This routine is adapted from FUNCTION RAN1 in Press, et al., 1986, Numerical Recipes, p196, Press Syndicate, NY. To reset the random number sequence, set _randseed to any negative number prior to calling this function, or one that depends on it (eg, RandNorm()).
This code is preferable in terms of portability as well as consistency across compilers.
cwb - 6/20/00
Returns
double. A value between 0 and 1.
RandUniList()
void RandUniList (long count, long first, long last, RandListType list[])
RandUniRange()
int RandUniRange (const long first, const long last)
Generate a random integer between two numbers.
Return a randomly selected integer between first and last, inclusive.
cwb - 12/5/00
cwb - 12/8/03 - just noticed that the previous version only worked with positive numbers and when first < last. Now it works with negative numbers as well as reversed order.
Examples:
first = 1, last = 10, result = 6
first = 5, last = -1, result = 2
first = -5, last = 5, result = 0
Parameters
first. One bound of the range between two numbers. A const long argument.
last. One bound of the range between two numbers. A const long argument.
Returns
integer. Random number between the two bounds defined.
Referenced by RandUniList().
Variable Documentation
_randseed
long _randseed = 0L
Referenced by RandSeed(), and RandUni_good().