name: docs

on:
  push:
    branches: [master, main, release/**]
  pull_request:
    branches: [master, main, release/**]


jobs:
  check_documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install doxygen and dependencies
      # SOILWAT2 documentation uses bibtex to build references
      run: |
        sudo apt-get update
        sudo apt-get install doxygen doxygen-latex graphviz

    - name: Build documentation and check for warnings
      run: make clean clean_doc doc
