name: simulation-checks-macos

# Checks: compilation, example run, and unit tests

on:
    push:
        branches: [master, main, release/**]
    pull_request:
        branches: [master, main, release/**]

jobs:
    macos-latest-checks:
        strategy:
            fail-fast: false
            matrix:
                sw2mode: [SWTXT, SWNC]
            max-parallel: 3
        uses: ./.github/workflows/simulation-checks.yml
        with:
          os: macos-latest
          sw2mode: ${{ matrix.sw2mode }}
