name: docs

on:
  push:
    branches: [master, main, release/**]
  pull_request:
    branches: [master, main, release/**]


jobs:
  check_documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install doxygen and dependencies
      # SOILWAT2 documentation requires doxygen > v1.9.8
      uses: ssiwr/doxygen-install@v1
      with:
        version: "1.11.0"

    - name: Build documentation and check for warnings
      run: make clean clean_doc doc
