name: win-tests

#TODO: run unit tests with different compiler versions of both gcc and clang

on:
  push:
    branches: [master, main, release/**]
  pull_request:
    branches: [master, main, release/**]

jobs:
  build_Windows_Cygwin:
    # see https://github.com/cygwin/cygwin-install-action
    # based on https://github.com/resurrecting-open-source-projects/scrot

    runs-on: windows-latest
    env:
      CYGWIN_NOWINPATH: 1 # only have cygwin's executables on PATH
      CHERE_INVOKING: 1 # prevent profile script to change directory
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login -eo pipefail -o igncr {0}

    steps:
    - run: git config --global core.autocrlf input
      shell: bash

    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install cygwin (windows)
      uses: cygwin/cygwin-install-action@v3
      with:
        packages: gcc-core gcc-g++ make

    - name: Print compiler versions as seen by make
      run: make compiler_version

    # AddressSanitizer and LeakSanitizer not available on cygwin
    - name: Run binary
      run: make clean bin_run

    - name: Unit tests (shuffle and repeat 3x)
      run: make clean test_rep3rnd

    - name: Unit tests RNG Seeding only
      run: |
        make clean_test test
        bin/sw_test --gtest_filter=AllTest.WeatherGeneratorRNGSeeding:AllTest.SitePTFsDeathTest

    - name: Unit tests (seed 2998)
      run: |
        make clean_test test
        bin/sw_test --gtest_shuffle --gtest_random_seed=2998

    - name: Unit tests (seed 71212)
      run: |
        make clean_test test
        bin/sw_test --gtest_shuffle --gtest_random_seed=71212
