name: win-tests

#TODO: run unit tests with different compiler versions of both gcc and clang

on:
  push:
    branches: [master, main, release/**]
  pull_request:
    branches: [master, main, release/**]

jobs:
  build_Windows_Cygwin:
    # see https://github.com/cygwin/cygwin-install-action
    # based on https://github.com/resurrecting-open-source-projects/scrot

    runs-on: windows-latest
    env:
      CYGWIN_NOWINPATH: 1 # only have cygwin's executables on PATH
      CHERE_INVOKING: 1 # prevent profile script to change directory
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login -eo pipefail -o igncr {0}

    steps:
    - run: git config --global core.autocrlf input
      shell: bash

    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install cygwin (windows)
      uses: cygwin/cygwin-install-action@v5
      with:
        allow-test-packages: true
        packages: gcc-core=14.2.1+20250222-0.1,gcc-g++=14.2.1+20250222-0.1,make

    - name: Print compiler versions as seen by make
      run: make compiler_version

    # AddressSanitizer and LeakSanitizer not available on cygwin
    - name: Run binary
      run: make clean bin_run

    - name: Unit tests (shuffle and repeat 3x)
      run: make clean test_rep3rnd

    - name: Compile as library for STEPWAT2
      run: CPPFLAGS='-DSTEPWAT' sw_sources='SW_Output_outarray.c SW_Output_outtext.c' make clean lib

    - name: Compile as library for rSOILWAT2
      run: CPPFLAGS='-DRSOILWAT' CFLAGS='-Iexternal/Rmock' sw_sources='SW_Output_outarray.c' make clean libr
